// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartFactorySystem.Infrastructure.Data;

#nullable disable

namespace SmartFactorySystem.Infrastructure.Migrations
{
    [DbContext(typeof(FactoryDbContext))]
    [Migration("20260601224431_AddMESFields")]
    partial class AddMESFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SmartFactorySystem.Application.Models.MachineStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualProductionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentWorkOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefectCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastStatusChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedProductionCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StandardCycleTimeSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StopReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MachineStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActualProductionCount = 450,
                            CurrentWorkOrder = "WO-2026-0001",
                            DefectCount = 2,
                            LastStatusChangedAt = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MachineId = "LINE-A-PRSS",
                            MachineName = "Aライン 高速プレス機",
                            PlannedProductionCount = 1000,
                            StandardCycleTimeSeconds = 10.5,
                            Status = "Running"
                        },
                        new
                        {
                            Id = 2,
                            ActualProductionCount = 120,
                            CurrentWorkOrder = "WO-2026-0001",
                            DefectCount = 0,
                            LastStatusChangedAt = new DateTime(2026, 6, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MachineId = "LINE-B-WELD",
                            MachineName = "Bライン 溶接ロボットアーム",
                            PlannedProductionCount = 500,
                            StandardCycleTimeSeconds = 10.5,
                            Status = "PlannedStop",
                            StopReason = "型替え作業中（段取り）"
                        },
                        new
                        {
                            Id = 3,
                            ActualProductionCount = 1800,
                            CurrentWorkOrder = "WO-2026-0001",
                            DefectCount = 45,
                            LastStatusChangedAt = new DateTime(2026, 6, 1, 11, 15, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MachineId = "LINE-C-PCKG",
                            MachineName = "Cライン 自動梱包機",
                            PlannedProductionCount = 2000,
                            StandardCycleTimeSeconds = 10.5,
                            Status = "Error",
                            StopReason = "搬送ベルト コンボイ詰まり"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
